SELECT NOME, SOBRENOME, EXTRACT(YEAR FROM AGE(DATA_NASC)) as idade FROM USUARIO
WHERE TIPO = 'Locatário' and EXTRACT(YEAR FROM AGE(DATA_NASC)) < ANY(
    SELECT EXTRACT(YEAR FROM AGE(DATA_NASC)) FROM USUARIO
    WHERE TIPO = 'Anfitrião'
);

SELECT NOME, SOBRENOME, EXTRACT(YEAR FROM AGE(DATA_NASC)) as idade FROM USUARIO
WHERE TIPO = 'Locatário' and EXTRACT(YEAR FROM AGE(DATA_NASC)) < ALL(
    SELECT EXTRACT(YEAR FROM AGE(DATA_NASC)) FROM USUARIO
    WHERE TIPO = 'Anfitrião'
);
