SELECT SUM(PRECO_NOITE)/COUNT(*) as MEDIA_DIARIA FROM PROPRIEDADE as P join RESERVA as R  
ON (P.NOME, P.ENDERECO) = (R.NOME_PROPRIEDADE, R.ENDERECO_PROPRIEDADE);

SELECT EXTRACT(MONTH FROM R.CHECK_IN) as MES, COUNT(*) as LOCACOES_CONFIRMADAS, SUM(P.PRECO_NOITE)/COUNT(*) as MEDIA_DIARIA FROM PROPRIEDADE as P join RESERVA as R  
ON (P.NOME, P.ENDERECO) = (R.NOME_PROPRIEDADE, R.ENDERECO_PROPRIEDADE)
WHERE R.STATUS = 'Confirmado' or R.STATUS = 'Pago'
GROUP BY MES
ORDER BY MES;
