SELECT LOCACAO, NOME_PROPRIEDADE, ENDERECO_PROPRIEDADE, NOME_LOCATARIO, SOBRENOME_LOCATARIO, TEL_LOCATARIO FROM RESERVA 
WHERE CHECK_IN > TIMESTAMP '2024-04-01' AND (STATUS = 'Confirmado' OR STATUS = 'Pago');

SELECT LOCACAO, EXTRACT(DAY FROM (CHECK_OUT - CHECK_IN)) as DIAS FROM RESERVA 
WHERE CHECK_IN > TIMESTAMP '2024-04-01' AND (STATUS = 'Confirmado' OR STATUS = 'Pago');

SELECT R.LOCACAO, P.NOME_ANF, P.SOBRENOME_ANF, R.NOME_LOCATARIO, R.SOBRENOME_LOCATARIO FROM PROPRIEDADE as P join RESERVA as R 
ON (P.NOME, P.ENDERECO) = (R.NOME_PROPRIEDADE, R.ENDERECO_PROPRIEDADE)
WHERE CHECK_IN > TIMESTAMP '2024-04-01' AND (STATUS = 'Confirmado' OR STATUS = 'Pago');

SELECT R.LOCACAO, P.PRECO_NOITE FROM PROPRIEDADE as P join RESERVA as R 
ON (P.NOME, P.ENDERECO) = (R.NOME_PROPRIEDADE, R.ENDERECO_PROPRIEDADE)
WHERE CHECK_IN > TIMESTAMP '2024-04-01' AND (STATUS = 'Confirmado' OR STATUS = 'Pago');


