SELECT 
    T3.NOME_ANF, T3.SOBRENOME_ANF, T3.N_PROPRIEDADES, T3.LOCACOES, U.CIDADE 
FROM 
    (
    SELECT T1.N_PROPRIEDADES, T2.LOCACOES,T1.NOME_ANF, T1.SOBRENOME_ANF, T1.TEL_ANF FROM
        (
        SELECT COUNT(*) as N_PROPRIEDADES, NOME_ANF, SOBRENOME_ANF, TEL_ANF FROM PROPRIEDADE GROUP BY NOME_ANF, SOBRENOME_ANF, TEL_ANF
        ) as T1
        
        JOIN
        (
            SELECT COUNT(*) as LOCACOES, P.NOME_ANF, P.SOBRENOME_ANF, TEL_ANF FROM PROPRIEDADE as P JOIN RESERVA as R
            ON (P.NOME, P.ENDERECO) = (R.NOME_PROPRIEDADE, R.ENDERECO_PROPRIEDADE)
            GROUP BY P.NOME_ANF, P.SOBRENOME_ANF, P.TEL_ANF
            HAVING COUNT(*) >= 3
        ) as T2
        ON (T1.NOME_ANF, T1.SOBRENOME_ANF, T1.TEL_ANF) = (T2.NOME_ANF, T2.SOBRENOME_ANF, T2.TEL_ANF)
    ) as T3 JOIN USUARIO AS U
ON 
    (T3.NOME_ANF, T3.SOBRENOME_ANF, T3.TEL_ANF) = (U.NOME, U.SOBRENOME, U.TELEFONE);

