SELECT * FROM PROPRIEDADE;

SELECT TIPO, COUNT(*) FROM PROPRIEDADE
GROUP BY TIPO;

SELECT FORMA_USO, COUNT(*) FROM PROPRIEDADE
WHERE TIPO = 'Quarto'
GROUP BY FORMA_USO;

SELECT CIDADE, COUNT(*) FROM PROPRIEDADE 
GROUP BY CIDADE;
